
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENORQ = 14;
  public static final int ENTERO = 5;
  public static final int CHARVAR = 21;
  public static final int RESTA = 27;
  public static final int IGUAL = 10;
  public static final int COLUMN = 39;
  public static final int CORDER = 23;
  public static final int DIV = 29;
  public static final int ENDPROGRAM = 18;
  public static final int GUION = 16;
  public static final int SUMA = 26;
  public static final int MIN = 36;
  public static final int ID = 7;
  public static final int MEDIANA = 32;
  public static final int EOF = 0;
  public static final int PARIZQ = 3;
  public static final int DECIMAL = 8;
  public static final int error = 1;
  public static final int PROGRAM = 17;
  public static final int COMA = 9;
  public static final int CADENA = 6;
  public static final int MODA = 33;
  public static final int MOD = 30;
  public static final int MAYORQ = 19;
  public static final int IDARR = 25;
  public static final int VARIANZA = 34;
  public static final int DOSP = 13;
  public static final int END = 15;
  public static final int MULTI = 28;
  public static final int ARR = 24;
  public static final int MEDIA = 31;
  public static final int DOUBLEVAR = 12;
  public static final int PARDER = 2;
  public static final int CORIZQ = 22;
  public static final int MAX = 35;
  public static final int VAR = 11;
  public static final int CONSOLE = 38;
  public static final int PRINT = 37;
  public static final int PYC = 4;
  public static final int MAS = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PARDER",
  "PARIZQ",
  "PYC",
  "ENTERO",
  "CADENA",
  "ID",
  "DECIMAL",
  "COMA",
  "IGUAL",
  "VAR",
  "DOUBLEVAR",
  "DOSP",
  "MENORQ",
  "END",
  "GUION",
  "PROGRAM",
  "ENDPROGRAM",
  "MAYORQ",
  "MAS",
  "CHARVAR",
  "CORIZQ",
  "CORDER",
  "ARR",
  "IDARR",
  "SUMA",
  "RESTA",
  "MULTI",
  "DIV",
  "MOD",
  "MEDIA",
  "MEDIANA",
  "MODA",
  "VARIANZA",
  "MAX",
  "MIN",
  "PRINT",
  "CONSOLE",
  "COLUMN"
  };
}

