
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENORQ = 16;
  public static final int ENTERO = 6;
  public static final int GRAPHPIE = 41;
  public static final int CHARVAR = 22;
  public static final int RESTA = 28;
  public static final int GRAPHBAR = 48;
  public static final int EJEY = 50;
  public static final int EJEX = 49;
  public static final int IGUAL = 11;
  public static final int COLUMN = 40;
  public static final int CORDER = 24;
  public static final int TITULO = 42;
  public static final int DIV = 30;
  public static final int ENDPROGRAM = 20;
  public static final int GUION = 18;
  public static final int SUMA = 27;
  public static final int MIN = 37;
  public static final int ID = 8;
  public static final int EXCL = 2;
  public static final int MEDIANA = 33;
  public static final int EOF = 0;
  public static final int PARIZQ = 4;
  public static final int DECIMAL = 9;
  public static final int error = 1;
  public static final int PROGRAM = 19;
  public static final int COMA = 10;
  public static final int CADENA = 7;
  public static final int VALUES = 44;
  public static final int MODA = 34;
  public static final int MOD = 31;
  public static final int TITY = 52;
  public static final int TITX = 51;
  public static final int GRAPPIE = 46;
  public static final int MAYORQ = 21;
  public static final int IDARR = 26;
  public static final int VARIANZA = 35;
  public static final int GRAPBAR = 47;
  public static final int DOSP = 15;
  public static final int END = 17;
  public static final int MULTI = 29;
  public static final int ARR = 25;
  public static final int MEDIA = 32;
  public static final int DOUBLEVAR = 14;
  public static final int EXEC = 45;
  public static final int PARDER = 3;
  public static final int LABEL = 43;
  public static final int CORIZQ = 23;
  public static final int MAX = 36;
  public static final int HISTOGRAM = 55;
  public static final int GRAPHLINE = 53;
  public static final int VAR = 13;
  public static final int GRAPLINE = 54;
  public static final int CONSOLE = 39;
  public static final int PRINT = 38;
  public static final int PYC = 5;
  public static final int MAS = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "EXCL",
  "PARDER",
  "PARIZQ",
  "PYC",
  "ENTERO",
  "CADENA",
  "ID",
  "DECIMAL",
  "COMA",
  "IGUAL",
  "MAS",
  "VAR",
  "DOUBLEVAR",
  "DOSP",
  "MENORQ",
  "END",
  "GUION",
  "PROGRAM",
  "ENDPROGRAM",
  "MAYORQ",
  "CHARVAR",
  "CORIZQ",
  "CORDER",
  "ARR",
  "IDARR",
  "SUMA",
  "RESTA",
  "MULTI",
  "DIV",
  "MOD",
  "MEDIA",
  "MEDIANA",
  "MODA",
  "VARIANZA",
  "MAX",
  "MIN",
  "PRINT",
  "CONSOLE",
  "COLUMN",
  "GRAPHPIE",
  "TITULO",
  "LABEL",
  "VALUES",
  "EXEC",
  "GRAPPIE",
  "GRAPBAR",
  "GRAPHBAR",
  "EJEX",
  "EJEY",
  "TITX",
  "TITY",
  "GRAPHLINE",
  "GRAPLINE",
  "HISTOGRAM"
  };
}

